

services:
  postgres:
    image: postgres:13
    container_name: nestjs-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nestjs-postgres
    ports:
      - "5432:5432"
    